api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']

  formats: 
    jsonld: [application/ld+json]
    json: [application/json]
    html: ['text/html']
    multipart: ['multipart/form-data']

  collection:
    pagination:
      items_per_page: 100

 